import type { Config } from "tailwindcss";

// Design tokens transcribed from the "Verdant Waters" design system
// (see verdant_waters/DESIGN.md in the original Stitch export).
const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./data/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#40493d",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        outline: "#707a6c",
        "outline-variant": "#bfcaba",
        "surface-tint": "#1b6d24",
        primary: "#0d631b",
        "on-primary": "#ffffff",
        "primary-container": "#2e7d32",
        "on-primary-container": "#cbffc2",
        "inverse-primary": "#88d982",
        secondary: "#546067",
        "on-secondary": "#ffffff",
        "secondary-container": "#d7e4ec",
        "on-secondary-container": "#5a666d",
        tertiary: "#006058",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#007b71",
        "on-tertiary-container": "#b3fff4",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#a3f69c",
        "primary-fixed-dim": "#88d982",
        "on-primary-fixed": "#002204",
        "on-primary-fixed-variant": "#005312",
        "secondary-fixed": "#d7e4ec",
        "secondary-fixed-dim": "#bbc8d0",
        "on-secondary-fixed": "#111d23",
        "on-secondary-fixed-variant": "#3c494f",
        "tertiary-fixed": "#84f5e8",
        "tertiary-fixed-dim": "#66d9cc",
        "on-tertiary-fixed": "#00201d",
        "on-tertiary-fixed-variant": "#005049",
        background: "#f9f9f9",
        "on-background": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        "background-white": "#ffffff",
        "surface-glass": "rgba(255, 255, 255, 0.8)",
        "price-green": "#1b5e20",
        "error-red": "#d32f2f",
      },
      fontFamily: {
        display: ["var(--font-poppins)", "Poppins", "sans-serif"],
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "56px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "display-lg-mobile": [
          "36px",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "price-display": ["20px", { lineHeight: "1", fontWeight: "700" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "section-gap": "120px",
        "section-gap-mobile": "64px",
        "edge-margin-desktop": "80px",
        "edge-margin-mobile": "20px",
      },
      maxWidth: {
        container: "1440px",
      },
      boxShadow: {
        soft: "0 10px 30px rgba(0, 0, 0, 0.05)",
        "soft-hover": "0 15px 40px rgba(0, 0, 0, 0.08)",
      },
      transitionTimingFunction: {
        soft: "cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [],
};

export default config;
